### ISSUE TITLE
Rustup fails on Mac OS X 10.12.4

### ISSUE THREAD

**Issue by JasonQSY** [rust-lang/rustup#1042]
On mac os x 10.12.4, when I run `curl https://sh.rustup.rs -sSf | sh`, it shows

```
info: downloading installer
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `2`, right: `1`)', src/rustup-cli/self_update.rs:495
stack backtrace:
   1:        0x105cca20a - std::sys::imp::backtrace::tracing::imp::write::he3d1bfbdbf113480
   2:        0x105cd224f - std::panicking::default_hook::{{closure}}::h575f1b40d2e88f07
   3:        0x105cd0edf - std::panicking::default_hook::h3d5dccce8125d0cf
   4:        0x105cd1516 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
   5:        0x105cd13b4 - std::panicking::begin_panic::ha6a0d553db9869ff
   6:        0x105cd12d2 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
   7:        0x105ac38bf - rustup_init::self_update::install::h90ee439c9b6ab7e9
   8:        0x105ad0f4d - rustup_init::run_multirust::hcf1b092d2ea80abf
   9:        0x105acf939 - rustup_init::main::h1a642123296d704d
  10:        0x105cd280a - __rust_maybe_catch_panic
  11:        0x105cd18b6 - std::rt::lang_start::h74b3afbdd8daef1c
rustup: command failed: /var/folders/zd/ncfnjr8d6v3c6fj3yg3t22qw0000gn/T/tmp.DlVXfBXT/rustup-init
```

I also try to download `rustup-init` manually, but it shows the same error. Hence, I think there might be some problem in `rustup-init`. I'm not familiar with `rust` thus unable to provide possible problem. But if you need more information to reproduce it, I'll willing to help.

**Comment by sigmavirus24** [comment]
I'm also encountering this on Fedora 25

```
~ ❯❯❯ uname -a 
Linux 4.9.5-200.fc25.x86_64 #1 SMP Fri Jan 20 12:24:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

For what it's worth, I'm using zsh.

My backtrace is:

```
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `2`, right: `1`)', src/rustup-cli/self_update.rs:495
stack backtrace:
   1:     0x561bc4a3e9ea - std::sys::imp::backtrace::tracing::imp::write::he3d1bfbdbf113480
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x561bc4a4873f - std::panicking::default_hook::{{closure}}::h575f1b40d2e88f07
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x561bc4a469c6 - std::panicking::default_hook::h3d5dccce8125d0cf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x561bc4a47077 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x561bc4a46f04 - std::panicking::begin_panic::ha6a0d553db9869ff
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x561bc4a46e29 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x561bc46a1a67 - rustup_init::self_update::install::h94b0e77a688fd64e
   8:     0x561bc46aff72 - rustup_init::run_multirust::ha3efb3064428696a
   9:     0x561bc46ae893 - rustup_init::main::h941855b00db4d6f6
  10:     0x561bc4a5021a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  11:     0x561bc4a47a95 - std::rt::lang_start::h74b3afbdd8daef1c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  12:     0x7f44b512d400 - __libc_start_main
  13:     0x561bc4676cb8 - <unknown>
rustup: command failed: /tmp/sigmavirus24/tmp.keYIHUANnv/rustup-init
```

**Comment by karamosky** [comment]
+1

**Comment by andrewrabert** [comment]
Same on up-to-date (w/ testing repos) Arch Linux box:

```
info: downloading installer
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `2`, right: `1`)', src/rustup-cli/self_update.rs:495
stack backtrace:
   1:     0x559f312019ea - std::sys::imp::backtrace::tracing::imp::write::he3d1bfbdbf113480
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x559f3120b73f - std::panicking::default_hook::{{closure}}::h575f1b40d2e88f07
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:247
   3:     0x559f312099c6 - std::panicking::default_hook::h3d5dccce8125d0cf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:263
   4:     0x559f3120a077 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:451
   5:     0x559f31209f04 - std::panicking::begin_panic::ha6a0d553db9869ff
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:413
   6:     0x559f31209e29 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:397
   7:     0x559f30e64a67 - rustup_init::self_update::install::h94b0e77a688fd64e
   8:     0x559f30e72f72 - rustup_init::run_multirust::ha3efb3064428696a
   9:     0x559f30e71893 - rustup_init::main::h941855b00db4d6f6
  10:     0x559f3121321a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libpanic_unwind/lib.rs:97
  11:     0x559f3120aa95 - std::rt::lang_start::h74b3afbdd8daef1c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panicking.rs:332
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/obj/../src/libstd/rt.rs:57
  12:     0x7fce75101510 - __libc_start_main
  13:     0x559f30e39cb8 - <unknown>
rustup: command failed: /tmp/tmp.ag4VIww2UN/rustup-init
```

**Comment by andrewrabert** [comment]
Running the command with the `-y` flag fixes the issue:

```
curl https://sh.rustup.rs > rustup.sh && sh rustup.sh -y  
```

CI seems to use this flag so I'm guessing that's why tests pass.

**Comment by JasonQSY** [comment]
Yes, downloading `rustup-init` and typing
```
./rustup-init -y
```
also solves the problem. However, it need to be fixed.

**Comment by JasonQSY** [comment]
@nvllsvm thanks 👍

**Comment by brson** [comment]
Seems like there's some problem accessing the tty. It probably will require somebody with such a system to debug.

**Comment by sigmavirus24** [comment]
@brson if you provide instructions, I'll try to debug this tonight or tomorrow night.

**Comment by Diggsey** [comment]
@sigmavirus24 Hi, thanks for offering! Here are the steps I think should be taken:
1) Verify that the issue can be reproduced with the latest version of rustup
2) Get rustup building from source (see the readme for instructions, and feel free to ask if you have any issues)
3) Run the compiled `rustup-init`, and reproduce the issue with that one (I recommend overriding `CARGO_HOME` and `RUSTUP_HOME` temporarily while running it, so that it won't affect your normal installation)
4) Obtain a new backtrace with rustup compiled in debug mode
5) Use your preferred debugging technique to narrow down exactly which assertion is failing, if it's not obvious from the backtrace. (From the previous backtrace it seems to be in `fn install(..)` from `self_update.rs` - maybe try commenting out lines from there to see where it's failing)

Once we know exactly which assertion is failing, it shouldn't be too hard to figure out the problem, but feel free to go further if you'd like - it's always good to have more contributors!

**Comment by nodakai** [comment]
FYI, the latest `rustup-init` is working fine without `-y` on macOS 10.13.4 (17E199)

**Comment by kinnison** [comment]
On the basis there has been no movement since July 2018, I'm going to close this.  If it reproduces on a modern `rustup` then please open a fresh issue.  Thanks.
