### ISSUE TITLE
Panic because `supplied instant is later than self` during download.

### ISSUE THREAD

**Issue by kinnison** [rust-lang/rustup#1984]
While testing the release of 1.19.0 we had an unreproducible instance of the download of a component panicing because `supplied instant is later than self`

Since we don't use `Instant` anywhere in our code, this must be in a dependency, but until we get a traceback we can't do much about it.  This is therefore here to track.

If you can reproduce it, please comment below with a traceback.

**Comment by kinnison** [comment]
With Rust 1.39.0 the `Instant::saturating_duration_since()` method will be stabilised which we might be able to use in whatever dependency it turns out was panicing.  If we can ever recreate it.

**Comment by tbarusseau** [comment]
Hi! I'm trying to install `cargo`/`rustc` through `rustup` and have this issue. It's 100% reproducible on my setup which means that I can't get to install rust on my system for now.

For the record I'm running an amd64 debian buster virtual machine through Virtualbox on a 64-bit Windows 10 host.

The logs + full backtrace, hoping it can help narrow down the issue:

```
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-11-19, rust version 1.48.0 (7eac88abb 2020-11-16)
info: downloading component 'rustc'
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rust-docs'
info: downloading component 'rustfmt'
info: downloading component 'clippy'
info: removing previous version of component 'rustc'
warning: during uninstall component rustc was not found
info: removing previous version of component 'cargo'
warning: during uninstall component cargo was not found
info: removing previous version of component 'rust-std'
warning: during uninstall component rust-std was not found
info: removing previous version of component 'rust-docs'
warning: during uninstall component rust-docs was not found
info: removing previous version of component 'rustfmt'
warning: during uninstall component rustfmt was not found
info: removing previous version of component 'clippy'
warning: during uninstall component clippy was not found
info: installing component 'rustc'
info: Defaulting to 500.0 MiB unpack ram
 66.2 MiB /  66.2 MiB (100 %)   9.4 MiB/s in  7s ETA:  0s
  6 IO-ops /   6 IO-ops (100 %)   6 IOPS in  1s ETA:  0s    
info: installing component 'cargo'
thread 'CloseHandle' panicked at 'supplied instant is later than self', src/libstd/time.rs:263:9
stack backtrace:
   0:     0x564a49e40ffd - backtrace::backtrace::libunwind::trace::h812748238d609e46
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x564a49e40ffd - backtrace::backtrace::trace_unsynchronized::h7c97e818aebf09c8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x564a49e40ffd - std::sys_common::backtrace::_print_fmt::h60d914263b0ccd71
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x564a49e40ffd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf78227137afc7565
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x564a49acb24c - core::fmt::write::h543cdf60775f89bf
                               at src/libcore/fmt/mod.rs:1069
   5:     0x564a49e40904 - std::io::Write::write_fmt::h0c7f3ce24c679426
                               at src/libstd/io/mod.rs:1504
   6:     0x564a49e40105 - std::sys_common::backtrace::_print::h80e55e24be231368
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x564a49e40105 - std::sys_common::backtrace::print::h3b197b9c1261c865
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x564a49e40105 - std::panicking::default_hook::{{closure}}::ha6c807149ce20f8f
                               at src/libstd/panicking.rs:198
   9:     0x564a49e3f8f4 - std::panicking::default_hook::he49a9c12e358cc45
                               at src/libstd/panicking.rs:218
  10:     0x564a49e3f3b6 - std::panicking::rust_panic_with_hook::h93f74f5ef2f71f31
                               at src/libstd/panicking.rs:515
  11:     0x564a49e3f198 - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x564a49ac8cf0 - core::panicking::panic_fmt::h1ce7d3a6bb2a90c1
                               at src/libcore/panicking.rs:111
  13:     0x564a49acc262 - core::option::expect_failed::had9e664931119ad2
                               at src/libcore/option.rs:1260
  14:     0x564a49e50423 - core::option::Option<T>::expect::hcb4298d173deab9b
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/option.rs:347
  15:     0x564a49e50423 - std::time::Instant::duration_since::h4d72b6014220b740
                               at src/libstd/time.rs:263
  16:     0x564a49e50423 - <std::time::Instant as core::ops::arith::Sub>::sub::hdf250b9c6df84a4a
                               at src/libstd/time.rs:390
  17:     0x564a49e50423 - std::time::Instant::elapsed::h82809c4130efd46e
                               at src/libstd/time.rs:327
  18:     0x564a49d7503d - rustup::diskio::perform::hb6b43f0b9094e706
  19:     0x564a49d7ff2b - <F as threadpool::FnBox>::call_box::h0c435316ccfa4600
  20:     0x564a49e7346f - std::sys_common::backtrace::__rust_begin_short_backtrace::hcb386125793ca1b9
  21:     0x564a49e72bb1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hcfc98cd16b45c433
  22:     0x564a49e5c7aa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hf207c3654ee300a0
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  23:     0x564a49e5c7aa - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h66e0c6190e34816b
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  24:     0x564a49e5c7aa - std::sys::unix::thread::Thread::new::thread_start::h30687bc0b1c3cd55
                               at src/libstd/sys/unix/thread.rs:87
  25:     0x7ff045d0efa3 - start_thread
  26:     0x7ff045c254cf - clone
  27:                0x0 - <unknown>
  3 IO-ops /   4 IO-ops ( 75 %)   3 IOPS in  2s ETA:  0s^C  
```

It then gets stuck on the last line, incrementing the time for what seems forever. Let me know if you need additional details.

Edit: I kept re-trying and it endend up actually succeeding!... But most of the components aren't actually installed. 😭

**Comment by kinnison** [comment]
Thank you for the backtrace.  @rbtcollins this looks like it happens inside the diskio threaded stuff.

**Comment by SirCupOfReese** [comment]
For the record, @tbarusseau is not alone in this, I just got here from google after experiencing a near identical issue. I decided to learn Rust as I've been interested in the language recently, and spun up a new Ubuntu 20.04 installation on VirtualBox running on Windows 10. After a few minutes, I was greeted by an almost exact copy of the error log he posted.

**Comment by kinnison** [comment]
I have picked this to try and fix for tomorrow.  I can't guarantee what I do will be sufficient, but I can at least resolve the particular instance in the backtrace above.
