### ISSUE TITLE
rustup --default-toolchain nightly -y fails on s390x

### ISSUE THREAD

**Issue by mtreinish** [rust-lang/rustup#2225]
**Problem**

Trying to add an s390x travis job to my rust project (that needs nightly for pyo3) fails when running `rustup.sh --default-toolchain nightly -y fails on s390x` 

For example see (I set `RUST_BACKTRACE=full` there):
https://travis-ci.com/mtreinish/retworkx/jobs/285025218

```
info: downloading installer

info: profile set to 'default'

info: default host triple is s390x-unknown-linux-gnu

info: syncing channel updates for 'nightly-s390x-unknown-linux-gnu'

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(NativeTls(Normal(ErrorStack([Error { code: 604422254, library: "random number generator", function: "RAND_DRBG_instantiate", reason: "error retrieving entropy", file: "crypto/rand/drbg_lib.c", line: 342 }, Error { code: 604418162, library: "random number generator", function: "RAND_DRBG_generate", reason: "in error state", file: "crypto/rand/drbg_lib.c", line: 589 }, Error { code: 604422254, library: "random number generator", function: "RAND_DRBG_instantiate", reason: "error retrieving entropy", file: "crypto/rand/drbg_lib.c", line: 342 }, Error { code: 604422254, library: "random number generator", function: "RAND_DRBG_instantiate", reason: "error retrieving entropy", file: "crypto/rand/drbg_lib.c", line: 342 }, Error { code: 604418162, library: "random number generator", function: "RAND_DRBG_generate", reason: "in error state", file: "crypto/rand/drbg_lib.c", line: 589 }, Error { code: 604422254, library: "random number generator", function: "RAND_DRBG_instantiate", reason: "error retrieving entropy", file: "crypto/rand/drbg_lib.c", line: 342 }, Error { code: 604418162, library: "random number generator", function: "RAND_DRBG_generate", reason: "in error state", file: "crypto/rand/drbg_lib.c", line: 589 }, Error { code: 604422254, library: "random number generator", function: "RAND_DRBG_instantiate", reason: "error retrieving entropy", file: "crypto/rand/drbg_lib.c", line: 342 }, Error { code: 604418162, library: "random number generator", function: "RAND_DRBG_generate", reason: "in error state", file: "crypto/rand/drbg_lib.c", line: 589 }, Error { code: 604422254, library: "random number generator", function: "RAND_DRBG_instantiate", reason: "error retrieving entropy", file: "crypto/rand/drbg_lib.c", line: 342 }, Error { code: 604422254, library: "random number generator", function: "RAND_DRBG_instantiate", reason: "error retrieving entropy", file: "crypto/rand/drbg_lib.c", line: 342 }, Error { code: 604418162, library: "random number generator", function: "RAND_DRBG_generate", reason: "in error state", file: "crypto/rand/drbg_lib.c", line: 589 }, Error { code: 604422254, library: "random number generator", function: "RAND_DRBG_instantiate", reason: "error retrieving entropy", file: "crypto/rand/drbg_lib.c", line: 342 }, Error { code: 604418162, library: "random number generator", function: "RAND_DRBG_generate", reason: "in error state", file: "crypto/rand/drbg_lib.c", line: 589 }, Error { code: 336236609, library: "SSL routines", function: "SSL_CTX_new", reason: "malloc failure", file: "ssl/ssl_lib.c", line: 3090 }]))))', src/libcore/result.rs:1165:5

stack backtrace:

   0:      0x2aa09023850 - backtrace::backtrace::libunwind::trace::h65597d255cb1398b

                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88

   1:      0x2aa09023850 - backtrace::backtrace::trace_unsynchronized::h85fd8d34e214d876

                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66

   2:      0x2aa09023850 - std::sys_common::backtrace::_print_fmt::he35a37f9b8e4b952

                               at src/libstd/sys_common/backtrace.rs:77

   3:      0x2aa09023850 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he0e762d8ed66f8bc

                               at src/libstd/sys_common/backtrace.rs:61

   4:      0x2aa08b48e88 - core::fmt::write::h1f444f4312eb6c27

                               at src/libcore/fmt/mod.rs:1028

   5:      0x2aa09022f82 - std::io::Write::write_fmt::hfae316bf0dea24b4

                               at src/libstd/io/mod.rs:1412

   6:      0x2aa09022ba6 - std::sys_common::backtrace::_print::ha081546d159043e6

                               at src/libstd/sys_common/backtrace.rs:65

   7:      0x2aa09022ba6 - std::sys_common::backtrace::print::h5ae28d5a72f95be5

                               at src/libstd/sys_common/backtrace.rs:50

   8:      0x2aa09022ba6 - std::panicking::default_hook::{{closure}}::h00506bfaacab8ec5

                               at src/libstd/panicking.rs:188

   9:      0x2aa09021c68 - std::panicking::default_hook::h55fa199021de9a28

                               at src/libstd/panicking.rs:205

  10:      0x2aa09021c68 - std::panicking::rust_panic_with_hook::h61149c5bf815a5b0

                               at src/libstd/panicking.rs:464

  11:      0x2aa09021646 - std::panicking::continue_panic_fmt::h8c2cbca8aac85ef4

                               at src/libstd/panicking.rs:373

  12:      0x2aa090400a0 - rust_begin_unwind

                               at src/libstd/panicking.rs:302

  13:      0x2aa08b42012 - core::panicking::panic_fmt::hdeb7979ab6591473

                               at src/libcore/panicking.rs:139

  14:      0x2aa08b4a1b6 - core::result::unwrap_failed::h054dd680e6fcd38b

                               at src/libcore/result.rs:1165

  15:      0x2aa08b7d58e - download::reqwest_be::download::he3488bfbb146e9bc

  16:      0x2aa08fb2d4a - rustup::utils::utils::download_file_with_resume::h90865a55dcc02c11

  17:      0x2aa08f96344 - rustup::dist::download::DownloadCfg::download_and_check::h7dd65ddb27744687

  18:      0x2aa08f84c34 - rustup::dist::dist::dl_v2_manifest::h656f222c9fa2b9e9

  19:      0x2aa08f79592 - rustup::dist::dist::try_update_from_dist_::ha21f5f9f36430415

  20:      0x2aa08f5468e - rustup::toolchain::Toolchain::install::h0081e82be820499f

  21:      0x2aa08f528d4 - rustup::toolchain::Toolchain::install_from_dist::hada8af715a645c77

  22:      0x2aa08a4620e - rustup_init::self_update::install::h4b38d9028c8cb1e1

  23:      0x2aa08a5e0e2 - rustup_init::setup_mode::main::hee6082bee7c6f229

  24:      0x2aa08a63d80 - rustup_init::main::h48031ff0699bf45a

  25:      0x2aa089b8a32 - std::rt::lang_start::{{closure}}::hc555f34d5f93902b

  26:      0x2aa089b8552 - std::rt::lang_start::h67cf5b5163ea4eb5

  27:      0x3ff96c22ece - __libc_start_main

  28:      0x2aa089b3914 - <unknown>
```

Looking at the backtrace it might be an issue in reqwest since that's where it seems to fail before triggering the panic, but I figured that I should open it here since rustup is what is failing and we can move the issue over to reqwest if necessary.

For reference the PR adding the job: https://github.com/mtreinish/retworkx/pull/16

**Steps**

On s390x:
1. `wget https://sh.rustup.rs -O rustup.sh`
2. `sh rustup.sh --default-toolchain nightly -y`

**Possible Solution(s)**

**Notes**

Output of `rustup --version`:
Output of `rustup show`:

**Comment by rbtcollins** [comment]
Looks like an issue with openssl. 
```
Error(NativeTls(Normal(ErrorStack([
    Error { code: 604422254, library: "random number generator", function: "RAND_DRBG_instantiate", reason: "error retrieving entropy", file: "crypto/rand/drbg_lib.c", line: 342 }, 
   Error { code: 604418162, library: "random number generator", function: "RAND_DRBG_generate", reason: "in error state", file: "crypto/rand/drbg_lib.c", line: 589 }, 
   Error { code: 604422254, library: "random number generator", function: "RAND_DRBG_instantiate", reason: "error retrieving entropy", file: "crypto/rand/drbg_lib.c", line: 342 }, 
  ...
```

looks like it is looping through restart -> instantiate -> generate -> restart etc.

**Comment by mtreinish** [comment]
Thanks, that gave me enough of a hint to figure out a workaround for the ci job. Upgrading the travis config to use ubuntu 18.04 seems to avoid the panic. There is still be something going on with the s390x ubuntu 16.04 ssl package that is included the default travis image but I don't think it's worth keeping this open anymore if upgrading to a newer version of openssl fixed it.

**Comment by rbtcollins** [comment]
You're welcome; yes, I think the place to direct this is travis/Ubuntu, but for a 4 year old distro... shrug.
