### ISSUE TITLE
Can't  install rust on Ubuntu 20.04 in Windows Subsystem for Linux

### ISSUE THREAD

**Issue by owencraston** [rust-lang/rustup#2319]
**Problem**
1. went to install [rust](https://www.rust-lang.org/learn/get-started) with the  following command
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
2. I  chose the `default` install (1)
3. When I do this I get the following `panic`
```
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-04-23, rust version 1.43.0 (4fb7144ed 2020-04-20)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 12.0 MiB /  12.0 MiB (100 %)   7.5 MiB/s in  1s ETA:  0s
info: downloading component 'rust-std'
 17.5 MiB /  17.5 MiB (100 %)   7.5 MiB/s in  2s ETA:  0s
info: downloading component 'rustc'
 59.6 MiB /  59.6 MiB (100 %)   7.4 MiB/s in  8s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:166:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
   2:     0x7fb82cadbc9c - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x7fb82cadbc9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x7fb82c7ba81c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x7fb82cadb526 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x7fb82cadb19e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x7fb82cadb19e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x7fb82cadb19e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x7fb82cada943 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x7fb82cada943 - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x7fb82cada4be - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x7fb82cada450 - std::panicking::begin_panic_fmt::ha0f013e3301a9528
                               at src/libstd/panicking.rs:328
  13:     0x7fb82caaae86 - <rustup::diskio::threaded::Threaded as rustup::diskio::Executor>::join::hf33124263a81d2a4
  14:     0x7fb82caaa636 - core::ptr::real_drop_in_place::haa8255139d9471a2
  15:     0x7fb82c7d5190 - core::ptr::real_drop_in_place::h04c627b98e68397b
  16:     0x7fb82ca9e777 - rustup::dist::component::package::unpack_without_first_dir::h352b57d236248e9a
  17:     0x7fb82ca762f6 - rustup::dist::manifestation::Manifestation::update::h8c800deec8167b5b
  18:     0x7fb82ca64b8a - rustup::dist::dist::try_update_from_dist_::h113375517e7a85ca
  19:     0x7fb82ca4964c - rustup::toolchain::Toolchain::install::h048b51ffab245b48
  20:     0x7fb82ca46c8c - rustup::toolchain::Toolchain::install_from_dist::h00b9aafeb93470e5
  21:     0x7fb82c7143ee - rustup_init::self_update::install::h4cee0e396cee456b
  22:     0x7fb82c725ca2 - rustup_init::run_rustup_inner::ha545371fd2dc19a6
  23:     0x7fb82c722d64 - rustup_init::main::hba9a23e308c96901
  24:     0x7fb82c6b7a03 - std::rt::lang_start::{{closure}}::h1778d9ce6385bef5
  25:     0x7fb82c72c458 - main
  26:     0x7fb82c3270b3 - __libc_start_main
  27:     0x7fb82c6b4029 - <unknown>
thread panicked while panicking. 
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-04-23, rust version 1.43.0 (4fb7144ed 2020-04-20)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
 12.0 MiB /  12.0 MiB (100 %)   7.5 MiB/s in  1s ETA:  0s
info: downloading component 'rust-std'
 17.5 MiB /  17.5 MiB (100 %)   7.5 MiB/s in  2s ETA:  0s
info: downloading component 'rustc'
 59.6 MiB /  59.6 MiB (100 %)   7.4 MiB/s in  8s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:166:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
   2:     0x7fb82cadbc9c - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x7fb82cadbc9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x7fb82c7ba81c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x7fb82cadb526 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x7fb82cadb19e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x7fb82cadb19e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x7fb82cadb19e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x7fb82cada943 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x7fb82cada943 - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x7fb82cada4be - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x7fb82cada450 - std::panicking::begin_panic_fmt::ha0f013e3301a9528
                               at src/libstd/panicking.rs:328
  13:     0x7fb82caaae86 - <rustup::diskio::threaded::Threaded as rustup::diskio::Executor>::join::hf33124263a81d2a4
  14:     0x7fb82caaa636 - core::ptr::real_drop_in_place::haa8255139d9471a2
  15:     0x7fb82c7d5190 - core::ptr::real_drop_in_place::h04c627b98e68397b
  16:     0x7fb82ca9e777 - rustup::dist::component::package::unpack_without_first_dir::h352b57d236248e9a
  17:     0x7fb82ca762f6 - rustup::dist::manifestation::Manifestation::update::h8c800deec8167b5b
  18:     0x7fb82ca64b8a - rustup::dist::dist::try_update_from_dist_::h113375517e7a85ca
  19:     0x7fb82ca4964c - rustup::toolchain::Toolchain::install::h048b51ffab245b48
  20:     0x7fb82ca46c8c - rustup::toolchain::Toolchain::install_from_dist::h00b9aafeb93470e5
  21:     0x7fb82c7143ee - rustup_init::self_update::install::h4cee0e396cee456b
  22:     0x7fb82c725ca2 - rustup_init::run_rustup_inner::ha545371fd2dc19a6
  23:     0x7fb82c722d64 - rustup_init::main::hba9a23e308c96901
  24:     0x7fb82c6b7a03 - std::rt::lang_start::{{closure}}::h1778d9ce6385bef5
  25:     0x7fb82c72c458 - main
  26:     0x7fb82c3270b3 - __libc_start_main
  27:     0x7fb82c6b4029 - <unknown>
thread panicked while panicking. 
Illegal instruction (core dumped)
```
**Steps**

1. I followed the [Windows Subsystem for Linux Installation Guide for Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
2. I installed `Ubuntu` from [here](https://www.microsoft.com/en-ca/p/ubuntu/9nblggh4msv6?cid=msft_web_chart&activetab=pivot:overviewtab)
    - according to the description it installs `Ubuntu 20.04 LTS release`
3. run `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` in the `WSL` terminal

**Possible Solution(s)**
- despite the error being different I tried all the suggested solutions in [this stackoverlfow issue](https://stackoverflow.com/questions/52542965/rust-installation-fails-on-windows-subsystem-for-linux-could-not-rename-compone) but to no avail.

**Notes**

Output of `rustup --version`: `rustup 1.21.1 (7832b2ebe 2019-12-20)`
Output of `rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/owen/.rustup      

no active toolchain
```

##### Env variables
```
SHELL=/bin/bash       
WSL_DISTRO_NAME=Ubuntu
NAME=owen-dell        
PWD=/mnt/c/Users/16134
LOGNAME=owen
HOME=/home/owen
LANG=C.UTF-8
TERM=xterm-256color
LESSOPEN=| /usr/bin/lesspipe %s
USER=owen
SHLVL=1
WSLENV=
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/home/owen/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Intel/WiFi/bin/:/mnt/c/Program Files/Common Files/Intel/WirelessCommon/:/mnt/c/Program Files/Git/cmd:/mnt/c/Users/16134/.cargo/bin:/mnt/c/Users/16134/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/16134/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/16134/AppData/Local/hyper/app-3.0.2/resources/bin:/snap/bin
HOSTTYPE=x86_64
_=/usr/bin/env
```

**Comment by arcuru** [comment]
This is a dupe of #2245, there are details in that issue.
