### ISSUE TITLE
rustup panics while installing toolchain under WSL2 Ubuntu

### ISSUE THREAD

**Issue by walac** [rust-lang/rustup#2341]
**Problem**
I am running a Ubuntu 20.04 installation under Windows 10 WSL 2. When I try to install a toolchain, `rustup` panics.

**Steps**

When running `rustup install stable`, I get:

```
$ rustup install stable
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-05-07, rust version 1.43.1 (8d69840ab 2020-05-04)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:166:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `22`,
 right: `4`', src/libstd/sys/unix/thread.rs:166:21
stack backtrace:
   0:     0x7f236bedbc9c - backtrace::backtrace::libunwind::trace::h65597d255cb1398b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x7f236bedbc9c - backtrace::backtrace::trace_unsynchronized::hd4f479d7150ec4a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x7f236bedbc9c - std::sys_common::backtrace::_print_fmt::h015072984a2b172c
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x7f236bedbc9c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6df05d3335f32194
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x7f236bbba81c - core::fmt::write::h1f444f4312eb6c27
                               at src/libcore/fmt/mod.rs:1028
   5:     0x7f236bedb526 - std::io::Write::write_fmt::h8d147888220078ef
                               at src/libstd/io/mod.rs:1412
   6:     0x7f236bedb19e - std::sys_common::backtrace::_print::h8a6df0fa81d6af62
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x7f236bedb19e - std::sys_common::backtrace::print::h6f05b4733407e509
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x7f236bedb19e - std::panicking::default_hook::{{closure}}::h0d0a23bd02315dd8
                               at src/libstd/panicking.rs:188
   9:     0x7f236beda943 - std::panicking::default_hook::h8d15a9aecb4efac6
                               at src/libstd/panicking.rs:205
  10:     0x7f236beda943 - std::panicking::rust_panic_with_hook::hbe174577402a475d
                               at src/libstd/panicking.rs:464
  11:     0x7f236beda4be - std::panicking::continue_panic_fmt::h4d855dad868accf3
                               at src/libstd/panicking.rs:373
  12:     0x7f236beda450 - std::panicking::begin_panic_fmt::ha0f013e3301a9528
                               at src/libstd/panicking.rs:328
  13:     0x7f236beaae86 - <rustup::diskio::threaded::Threaded as rustup::diskio::Executor>::join::hf33124263a81d2a4
  14:     0x7f236beaa636 - core::ptr::real_drop_in_place::haa8255139d9471a2
  15:     0x7f236bbd5190 - core::ptr::real_drop_in_place::h04c627b98e68397b
  16:     0x7f236be9e777 - rustup::dist::component::package::unpack_without_first_dir::h352b57d236248e9a
  17:     0x7f236be762f6 - rustup::dist::manifestation::Manifestation::update::h8c800deec8167b5b
  18:     0x7f236be64b8a - rustup::dist::dist::try_update_from_dist_::h113375517e7a85ca
  19:     0x7f236be4964c - rustup::toolchain::Toolchain::install::h048b51ffab245b48
  20:     0x7f236be46c8c - rustup::toolchain::Toolchain::install_from_dist::h00b9aafeb93470e5
  21:     0x7f236bb05f1f - rustup_init::rustup_mode::update::hbe56e74e72e7ae31
  22:     0x7f236bada541 - rustup_init::rustup_mode::main::h2c97a39c05d9bf7c
  23:     0x7f236bb23b1c - rustup_init::run_rustup_inner::ha545371fd2dc19a6
  24:     0x7f236bb22d64 - rustup_init::main::hba9a23e308c96901
  25:     0x7f236bab7a03 - std::rt::lang_start::{{closure}}::h1778d9ce6385bef5
  26:     0x7f236bb2c458 - main
  27:     0x7f236b7770b3 - __libc_start_main
  28:     0x7f236bab4029 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction (core dumped)
```

**Notes**

```
$ rustup --version
rustup 1.21.1 (7832b2ebe 2019-12-20)
```

```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/walac/.rustup

no active toolchain
```

**Comment by rbtcollins** [comment]
Please supply the output of
```
wsl --list --verbose
```

**Comment by walac** [comment]
> Please supply the output of

My `wsl` doesn't support the `--verbose` option, I ran it with `--all`

```
> wsl --list --all
Windows Subsystem for Linux Distributions:
Ubuntu-20.04 (Default)
```

**Comment by workingjubilee** [comment]
Then it is almost certainly not WSL2, in spite of the misleading information you might have read. WSL2 and the `wsl --list --verbose` option came out at the same time.

**Comment by rbtcollins** [comment]
Dup of #2245
