### ISSUE TITLE
`rustup which cargo` panics if you specify a `--toolchain` which isn't installed

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rustup#2969]
### Problem

Rustup panics instead of giving a proper error message:

```
thread 'main' panicked at 'binary not found', src/cli/rustup_mode.rs:1053:6
```

<details>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1321:5
   3: rustup::cli::rustup_mode::main
   4: rustup_init::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

### Steps

1. `rustup which cargo --toolchain x`

### Possible Solution(s)

Print an error instead, the same way `cargo +x --version` does.
```
error: toolchain 'x' is not installed
```

### Rustup version

```console
rustup 1.24.3 (ce5817a94 2021-05-31)
```

### Installed toolchains

```console
more than you want to read - none are named `x` though
```

**Comment by kinnison** [comment]
I can confirm this behaviour:

```console
indolence(git)(🦀🏠)% rustup which cargo --toolchain x                                                               
thread 'main' panicked at 'binary not found', src/cli/rustup_mode.rs:1053:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: exit 101   rustup which cargo --toolchain x
indolence(git)(🦀🏠)% rustup +x which cargo                                                                          
error: override toolchain 'x' is not installed: the +toolchain on the command line specifies an uninstalled toolchain
zsh: exit 1     rustup +x which cargo
indolence(git)(🦀🏠)%                                                                                                
```

This needs fixing.

**Comment by kinnison** [comment]
Bah, I've now checked and while this behaviour is true in the released rustup, it's actually fixed on mainline.

So it doesn't need fixing so much as a new release needs making.

**Comment by kinnison** [comment]
1.25 is now out.
