### ISSUE TITLE
rustup update panics while trying to clean up tmp directory

### ISSUE THREAD

**Issue by magic-sysrq** [rust-lang/rustup#3381]
### Problem

**When i tried to run "rustup update" in the vs code powershell terminal, i got this output:**

info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
732.1 KiB / 732.1 KiB (100 %) 591.4 KiB/s in  1s ETA:  0s
info: latest update on 2023-06-01, rust version 1.70.0 (90c541806 2023-05-31)
info: downloading component 'rls'
info: downloading component 'rust-analysis'
info: downloading component 'rust-src'
  2.3 MiB /   2.3 MiB (100 %) 671.4 KiB/s in  2s ETA:  0s
info: downloading component 'cargo'
  4.7 MiB /   4.7 MiB (100 %)   1.5 MiB/s in  3s ETA:  0s
info: downloading component 'clippy'
  1.9 MiB /   1.9 MiB (100 %)   1.6 MiB/s in  1s ETA:  0s
info: downloading component 'rust-docs'
 13.5 MiB /  13.5 MiB (100 %)   2.0 MiB/s in  7s ETA:  0s
info: downloading component 'rust-std'
 25.1 MiB /  25.1 MiB (100 %) 610.1 KiB/s in 30s ETA:  0s    
info: downloading component 'rustc'
 60.6 MiB /  60.6 MiB (100 %) 236.8 KiB/s in  1m 46s ETA:  0s
info: downloading component 'rustfmt'
  1.4 MiB /   1.4 MiB (100 %)   1.0 MiB/s in  1s ETA:  0s
info: removing previous version of component 'rls'
info: removing previous version of component 'rust-analysis'
info: removing previous version of component 'rust-src'
info: removing previous version of component 'cargo'
info: removing previous version of component 'clippy'
info: removing previous version of component 'rust-docs'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rustfmt'
info: installing component 'rls'
info: installing component 'rust-analysis'
info: installing component 'rust-src'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
 25.1 MiB /  25.1 MiB (100 %)   7.3 MiB/s in  3s ETA:  0s
info: installing component 'rustc'
 60.6 MiB /  60.6 MiB (100 %)   9.5 MiB/s in 23s ETA:  0s
info: installing component 'rustfmt'
warning: could not delete temp file: C:\Users\norma\.rustup\tmp\rq4zmj3htgwj60ts_file
info: checking for self-update

  stable-x86_64-pc-windows-msvc updated - rustc 1.70.0 (90c541806 2023-05-31) (from rustc 1.69.0 (84c898d65 2023-04-16))

info: cleaning up downloads & tmp directories
thread 'main' panicked at 'Unable to clean up C:\Users\norma\.rustup\tmp: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\utils\utils.rs:650:13        
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PS C:\Users\norma\OneDrive\Pictures\CleanDeComputer> rustup update
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-update

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.70.0 (90c541806 2023-05-31)

info: cleaning up downloads & tmp directories
thread 'main' panicked at 'Unable to clean up C:\Users\norma\.rustup\tmp: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\utils\utils.rs:650:13        
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**After running it again in an admin powershell with RUST_BACKTRACE=full, i got this output:**

info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-update

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.70.0 (90c541806 2023-05-31)

info: cleaning up downloads & tmp directories
thread 'main' panicked at 'Unable to clean up C:\Users\norma\.rustup\tmp: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', src\utils\utils.rs:650:13
stack backtrace:
   0:     0x7ff71d3592e3 - <unknown>
   1:     0x7ff71cf88ddb - <unknown>
   2:     0x7ff71d334ae1 - <unknown>
   3:     0x7ff71d35df2b - <unknown>
   4:     0x7ff71d35daf7 - <unknown>
   5:     0x7ff71d35d6f5 - <unknown>
   6:     0x7ff71d35e79d - <unknown>
   7:     0x7ff71d35e4f6 - <unknown>
   8:     0x7ff71d35e43f - <unknown>
   9:     0x7ff71d35e414 - <unknown>
  10:     0x7ff71d486615 - <unknown>
  11:     0x7ff71d311ee5 - <unknown>
  12:     0x7ff71d2da597 - <unknown>
  13:     0x7ff71d2c3447 - <unknown>
  14:     0x7ff71cee2cf2 - <unknown>
  15:     0x7ff71cee1006 - <unknown>
  16:     0x7ff71cee3bd0 - <unknown>
  17:     0x7ff71d45848c - <unknown>
  18:     0x7ff967977614 - BaseThreadInitThunk
  19:     0x7ff9696826a1 - RtlUserThreadStart
  
  
  **When i tried to delete the file file in \.rustup\tmp, i got an error saying it is in use.**

### Steps

1. Open powershell/cmd/whatever
2. rustup update

### Rustup version

```console
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.70.0 (90c541806 2023-05-31)`
```

### Installed toolchains

```console
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\censoredmyname\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.70.0 (90c541806 2023-05-31)
```

**Comment by magic-sysrq** [comment]
I terminated the process in process hacker and now it ran successfully. :)
