### ISSUE TITLE
Panick on `rustup component add rust-analysis`

### ISSUE THREAD

**Issue by azerupi** [rust-lang/rustup#983]
I was following along with the setup of RLS and stumbled upon a panick in rustup. I was running the following command:

```
$ rustup component add rust-analysis
```

But it complained

```
error: toolchain 'stable-x86_64-apple-darwin' does not contain component 'rust-analysis' for target 'x86_64-apple-darwin'
```

So I tried to change the default toolchain to nightly and run the command again

```
$ rustup set default-host nightly
$ rustup component add rust-analysis
thread 'main' panicked at 'host triple couldn't be converted to partial triple', ../src/libcore/option.rs:705
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The backtrace gave the following:
```
RUST_BACKTRACE=1 rustup component add rust-analysis
thread 'main' panicked at 'host triple couldn't be converted to partial triple', ../src/libcore/option.rs:705
stack backtrace:
   1:        0x10e4bc25a - std::sys::imp::backtrace::tracing::imp::write::he3d1bfbdbf113480
   2:        0x10e4c429f - std::panicking::default_hook::{{closure}}::h575f1b40d2e88f07
   3:        0x10e4c2f2f - std::panicking::default_hook::h3d5dccce8125d0cf
   4:        0x10e4c3566 - std::panicking::rust_panic_with_hook::h00b81bb3dcbd51f2
   5:        0x10e4c3404 - std::panicking::begin_panic::ha6a0d553db9869ff
   6:        0x10e4c3322 - std::panicking::begin_panic_fmt::h24d113aee3ee4081
   7:        0x10e4c3287 - rust_begin_unwind
   8:        0x10e4f0580 - core::panicking::panic_fmt::he441b2ea2036b98a
   9:        0x10e4f05ed - core::option::expect_failed::h7136772e5b75d3f8
  10:        0x10e31e4a4 - rustup_dist::dist::PartialToolchainDesc::resolve::hb8b549e92e10461a
  11:        0x10e2f7434 - rustup::config::Cfg::resolve_toolchain::h3ab434a05f045dc7
  12:        0x10e2e3735 - rustup::toolchain::Toolchain::from::h8bdb1ab238d5678d
  13:        0x10e2f0d8e - rustup::config::Cfg::verify_toolchain::hb437148012f90f7b
  14:        0x10e2f25a5 - rustup::config::Cfg::find_default::hd154387dd269acfc
  15:        0x10e2f3e25 - rustup::config::Cfg::find_override_toolchain_or_default::h1e0ee658269c98a6
  16:        0x10e2f5595 - rustup::config::Cfg::toolchain_for_dir::hb664c018f9eb5b6d
  17:        0x10e2b04b7 - rustup_init::rustup_mode::explicit_or_dir_toolchain::hee88bd821b8859e6
  18:        0x10e29ea3e - rustup_init::rustup_mode::main::h407750f090a6dded
  19:        0x10e2c36a0 - rustup_init::run_multirust::h7701e04292061be6
  20:        0x10e2c2d39 - rustup_init::main::h6b97e65baef24abd
  21:        0x10e4c485a - __rust_maybe_catch_panic
  22:        0x10e4c3906 - std::rt::lang_start::h74b3afbdd8daef1c
```

**Comment by brson** [comment]
The problem here is that 'rustup set default-host nightly' allowed you to set a bogus triple. I'm not sure how to solve that right now. Probably just make this error case better.

**Comment by azerupi** [comment]
>The problem here is that 'rustup set default-host nightly' allowed you to set a bogus triple.

Could we check if the triple is installed and if not complain about that?

**Comment by kinnison** [comment]
I believe we do not setting a bad triple these days.
